# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  # username: kosmetic
  # password:
  # host: localhost
  # port: 5432
  # schema_search_path: myapp,sharedapp,public
  # min_messages: notice

development:
  <<: *default
  database: kosmetic_development

test:
  <<: *default
  database: kosmetic_test

production:
  <<: *default
  database: kosmetic_production
  username: kosmetic
  password: <%= ENV['KOSMETIC_DATABASE_PASSWORD'] %>
